project:
  type: website

website:
  title: "Geography 385: Spatial Data Analysis"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        menu:
          - text: "09-26 Course Overview"
            href: lectures/week01/lecture.qmd
          - text: "09-26 Spatial Data Analysis"
            href: lectures/week01/lecture_sda.qmd
      - text: "Studio"
        menu:
          - text: "Python Primer"
            href: studio/python_course.qmd
              #- text: "09-28 Juptyer"
              #href: studio/week01/jupyter.qmd
      - text: "References"
        menu:
          - text: "References"
            href: references.qmd
    right:
      - text: "About"
        href: about.qmd
  sidebar:
    - section: "Weeks"
      contents:
        - text: "09-26 Course Overview"
          href: lectures/week01/lecture.qmd
        - text: "09-26 Spatial Data Analysis"
          href: lectures/week01/lecture_sda.qmd
            #- text: "09-28 Jupyter"
            #  href: studio/week01/jupyter.qmd
    - section: "Resources"
      contents:
        - text: "Syllabus"
          href: syllabus.qmd

format:
  html:
    css: styles/custom.scss
    toc: true
    toc-depth: 2
    code-fold: true
    code-tools: true

bibliography: 385.bib
