project:
  type: website

website:
  title: "Geography 385: Spatial Data Analysis"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        menu:
          - text: "08-26 Course Overview"
            href: lectures/week01/index.qmd
      - text: "Studio"
        menu:
          - text: "08-28 Studio 1: Juptyer Hub Introduction"
            href: studio/week01/index.qmd
          - text: "09-04 Studio 2: Pandas"
            href: studio/week02/index.qmd
          - text: "09-11 Studio 3: GeoPandas"
            href: studio/week03/index.qmd
      - text: "References"
        href: references.qmd
    right:
      - text: "About"
        href: about.qmd
  sidebar:
    - section: "Weeks"
      contents:
        - text: "08-26 Course Overview"
          href: lectures/week01/index.qmd
        - text: "08-28 Studio 1: Jupyter Hub"
          href: studio/week01/index.qmd
        - text: "09-04 Studio 2: Pandas"
          href: studio/week02/index.qmd
        - text: "09-09 Spatial Data Analysis"
          href: lectures/week03/index.qmd
        - text: "09-11 Studio 3: GeoPandas"
          href: studio/week03/index.qmd
    - section: "Resources"
      contents:
        - text: "Syllabus"
          href: syllabus.qmd

format:
  html:
    css: styles/custom.scss
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true

bibliography: 385.bib
